/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 combinedoffice.glb --transform 
Files: combinedoffice.glb [48.3MB] > C:\Users\aasth\OneDrive\Documents\StoryProc3D\src\models\combinedoffice-transformed.glb [12.06MB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/combinedoffice-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig004" position={[2.976, 0, -2.527]} rotation={[0, 0.528, 0]} scale={0.703}>
          <primitive object={nodes.spine} />
        </group>
        <group name="metarig002" position={[-8.044, 0.017, -8.138]} rotation={[0, 0.706, 0]} scale={1.157}>
          <primitive object={nodes.spine_1} />
        </group>
        <group name="metarig006" position={[6.096, -0.383, -1.273]} rotation={[0, -1.561, 0]} scale={0.895}>
          <primitive object={nodes.spine_2} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <group name="metarig007" position={[6.095, -0.376, -3.173]} rotation={[0, -1.476, 0]} scale={0.891}>
          <primitive object={nodes.spine_3} />
        </group>
        <group name="metarig008" position={[1.645, -0.395, -3.165]} rotation={[0, -1.464, 0]} scale={0.891}>
          <group name="Object_81004" position={[0.018, -0.03, -0.02]} rotation={[0, -0.005, 0]} />
          <primitive object={nodes.spine_4} />
        </group>
        <group name="metarig009" position={[4.067, -0.392, -5.47]} rotation={[0, 1.523, 0]} scale={0.907}>
          <primitive object={nodes.spine_5} />
        </group>
        <group name="metarig010" position={[4.096, -0.339, -7.227]} rotation={[0, 1.57, 0]} scale={0.843}>
          <primitive object={nodes.spine_6} />
        </group>
        <group name="metarig011" position={[12.422, 0.022, -4.609]} rotation={[0, 1.488, 0]} scale={0.911}>
          <primitive object={nodes.spine_7} />
        </group>
        <group name="metarig012" position={[-8.618, -0.397, -4.241]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={1.022}>
          <primitive object={nodes.spine_8} />
        </group>
        <group name="metarig005" position={[-10.081, -0.433, 4.236]} rotation={[0, 1.096, 0]} scale={0.992}>
          <primitive object={nodes.spine_9} />
        </group>
        <group name="metarig013" position={[-3.961, -0.488, -4.483]} rotation={[Math.PI, -0.515, Math.PI]} scale={1.095}>
          <primitive object={nodes.spine_10} />
        </group>
        <group name="metarig014" position={[10.513, -0.376, -1.366]} rotation={[0, -1.571, 0]} scale={0.961}>
          <primitive object={nodes.spine_11} />
        </group>
        <group name="Female_Office006" position={[9.624, 0.236, -7.243]} rotation={[0, -1.567, 0]} scale={1.047}>
          <group name="Female007" />
          <primitive object={nodes.spine_12} />
          <primitive object={nodes.neutral_bone_1} />
          <group name="Mesh024">
            <skinnedMesh name="Mesh024_1" geometry={nodes.Mesh024_1.geometry} material={nodes.Mesh024_1.material} skeleton={nodes.Mesh024_1.skeleton} />
            <skinnedMesh name="Mesh024_2" geometry={nodes.Mesh024_2.geometry} material={materials['face.002']} skeleton={nodes.Mesh024_2.skeleton} />
            <skinnedMesh name="Mesh024_3" geometry={nodes.Mesh024_3.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh024_3.skeleton} />
            <skinnedMesh name="Mesh024_4" geometry={nodes.Mesh024_4.geometry} material={materials.orange2} skeleton={nodes.Mesh024_4.skeleton} />
          </group>
        </group>
        <group name="Female_Office008" position={[4.042, -0.063, -3.146]} rotation={[0, 1.526, 0]} scale={0.654}>
          <group name="Female009" />
          <primitive object={nodes.spine_13} />
          <primitive object={nodes.neutral_bone_2} />
          <primitive object={nodes.neutral_bone001} />
          <primitive object={nodes.neutral_bone002} />
          <group name="Mesh003">
            <skinnedMesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh003_1.skeleton} />
            <skinnedMesh name="Mesh003_2" geometry={nodes.Mesh003_2.geometry} material={materials['Material.016']} skeleton={nodes.Mesh003_2.skeleton} />
            <skinnedMesh name="Mesh003_3" geometry={nodes.Mesh003_3.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh003_3.skeleton} />
            <skinnedMesh name="Mesh003_4" geometry={nodes.Mesh003_4.geometry} material={materials.orgfabric} skeleton={nodes.Mesh003_4.skeleton} />
            <skinnedMesh name="Mesh003_5" geometry={nodes.Mesh003_5.geometry} material={materials['Material.034']} skeleton={nodes.Mesh003_5.skeleton} />
            <skinnedMesh name="Mesh003_6" geometry={nodes.Mesh003_6.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh003_6.skeleton} />
          </group>
        </group>
        <group name="Female_Office011" position={[14.662, -0.063, -3.476]} rotation={[Math.PI, -1.176, Math.PI]} scale={0.654}>
          <group name="Female012" />
          <primitive object={nodes.spine_14} />
          <primitive object={nodes.neutral_bone_3} />
          <primitive object={nodes.neutral_bone001_1} />
          <group name="Mesh005">
            <skinnedMesh name="Mesh005_1" geometry={nodes.Mesh005_1.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh005_1.skeleton} />
            <skinnedMesh name="Mesh005_2" geometry={nodes.Mesh005_2.geometry} material={materials['Material.016']} skeleton={nodes.Mesh005_2.skeleton} />
            <skinnedMesh name="Mesh005_3" geometry={nodes.Mesh005_3.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh005_3.skeleton} />
            <skinnedMesh name="Mesh005_4" geometry={nodes.Mesh005_4.geometry} material={materials.green2} skeleton={nodes.Mesh005_4.skeleton} />
          </group>
        </group>
        <group name="Female_Office007" position={[-6.502, -0.07, -3.778]} rotation={[-Math.PI, 0.038, -Math.PI]} scale={0.835}>
          <primitive object={nodes.spine_15} />
          <primitive object={nodes.neutral_bone_4} />
        </group>
        <group name="metarig003" position={[-9.435, 0, -5.998]} rotation={[-Math.PI, 0.474, -Math.PI]} scale={0.707}>
          <primitive object={nodes.spine_16} />
        </group>
        <group name="Female_Office009" position={[-7.524, 0.285, -3.954]} rotation={[-Math.PI, 0.142, -Math.PI]} scale={1.246}>
          <primitive object={nodes.spine_17} />
          <primitive object={nodes.neutral_bone_5} />
        </group>
        <group name="Object_4" position={[14.803, 0, 5.434]} rotation={[-Math.PI, 1.141, -Math.PI]} scale={0.758}>
          <primitive object={nodes._rootJoint} />
          <primitive object={nodes.neutral_bone_6} />
        </group>
        <group name="metarig" position={[17.063, -0.069, 5.175]} rotation={[0, -1.052, 0]} scale={0.731}>
          <primitive object={nodes.spine_18} />
        </group>
        <group name="Female_Office001" position={[5.641, -0.268, 3.956]} rotation={[0, -0.678, 0]} scale={0.654}>
          <primitive object={nodes.spine_19} />
          <primitive object={nodes.neutral_bone_7} />
          <primitive object={nodes.neutral_bone001_2} />
        </group>
        <group name="Man_Office1004" position={[3.314, -0.422, 5.755]} rotation={[-Math.PI, 1.065, -Math.PI]} scale={0.794}>
          <primitive object={nodes.spine_20} />
          <primitive object={nodes.neutral_bone_8} />
        </group>
        <mesh name="Cube095" geometry={nodes.Cube095.geometry} material={materials.table} position={[11.672, 1.219, -1.457]} />
        <group name="Plane020" position={[-7.86, 0.919, -5.472]} rotation={[-Math.PI, 0.364, -Math.PI]} scale={0.885}>
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['tv1.001']} />
          <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials['leather.001']} />
          <mesh name="Plane012_2" geometry={nodes.Plane012_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Mesa_con_sillas_reuniones_180_x_380_cm_392443" position={[-7.079, 0, -5.64]} scale={[0.441, 0.305, 0.305]}>
          <mesh name="Mesa_con_sillas_reuniones_180_x_380_cm_392443_384274_cc94869" geometry={nodes.Mesa_con_sillas_reuniones_180_x_380_cm_392443_384274_cc94869.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Mesa_con_sillas_reuniones_180_x_380_cm_392443_384274_cc94869_1" geometry={nodes.Mesa_con_sillas_reuniones_180_x_380_cm_392443_384274_cc94869_1.geometry} material={materials['Dark iron.001']} />
        </group>
        <mesh name="Silla_Silla_392447" geometry={nodes.Silla_Silla_392447.geometry} material={materials.PaletteMaterial003} position={[-5.812, 0, -4.527]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
        <mesh name="monsteralaf025" geometry={nodes.monsteralaf025.geometry} material={materials['monsteralaf.001']} position={[-10.251, 1.296, -8.149]} rotation={[-2.864, -0.172, -0.058]} scale={0.827} />
        <group name="Circle055" position={[-10.297, -0.014, -8.525]} rotation={[0, -1.562, 0]} scale={1.161}>
          <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials['Clay roof tile black']} />
          <mesh name="Circle007_1" geometry={nodes.Circle007_1.geometry} material={materials['Material.012']} />
        </group>
        <mesh name="Circle069" geometry={nodes.Circle069.geometry} material={materials.PaletteMaterial004} position={[-6.735, 0.904, -4.57]} rotation={[0, 0.761, 0]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.015']} position={[-7.06, 0.915, -4.78]} rotation={[0, 0.85, 0]} scale={[0.084, 0.072, 0.102]} />
        <group name="Ottoman_01005" position={[-9.662, 0, 6.585]} rotation={[0, -0.72, 0]} scale={[0.868, 1.078, 1.162]}>
          <mesh name="Mesh008" geometry={nodes.Mesh008.geometry} material={materials.Ottoman_01} />
          <mesh name="Mesh008_1" geometry={nodes.Mesh008_1.geometry} material={materials.darkbluefabric} />
        </group>
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials.beige} position={[-7.232, 0.274, 3.662]} rotation={[0, -1.571, 0]} scale={[1.185, 1.237, 1.185]} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials['Dark iron.002']} position={[-7.232, 0.274, 3.662]} rotation={[0, -1.571, 0]} scale={[1.185, 1.237, 1.185]} />
        <mesh name="Ottoman_01003" geometry={nodes.Ottoman_01003.geometry} material={materials.leatherbrown} position={[3.761, 0, 3.839]} rotation={[Math.PI, -0.503, Math.PI]} scale={[0.868, 1.1, 1.162]} />
        <mesh name="82625556_Boston_Fern-_Nephrolepis_Exaltata-_-6" geometry={nodes['82625556_Boston_Fern-_Nephrolepis_Exaltata-_-6'].geometry} material={materials['82625556_Boston Fern- Nephrolepis Exaltata- -6']} position={[-1.937, 0.792, -1.036]} rotation={[Math.PI / 2, 0, -1.044]} />
        <mesh name="Ottoman_01016" geometry={nodes.Ottoman_01016.geometry} material={materials.wood} position={[-8.434, 0.458, -1.649]} rotation={[0, 0.267, 0]} scale={[0.929, 0.873, 0.954]} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials['tv2.001']} position={[-6.822, 2.175, -8.994]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.keyboard} position={[9.156, 0.802, -6.974]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.001, 0.002, 0]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Material.034']} position={[9.124, 0.797, -7.456]} rotation={[Math.PI / 2, 0, 2.804]} scale={[0.001, 0, 0]} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={nodes.Cube059.material} position={[-6.835, 1.927, -9.322]} />
        <mesh name="monsteralaf005" geometry={nodes.monsteralaf005.geometry} material={materials.monsteralaf} position={[12.63, 1.018, -0.699]} rotation={[-1.336, 0.178, 0.999]} scale={0.006} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.painting} position={[-10.997, 2.19, 1.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.609, 1.056, 1.056]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.screen} position={[0.523, 0.752, -3.146]} rotation={[0, 0.018, 0]} scale={[0.041, 0.021, 0.041]} />
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['pngwing.com']} position={[-3.065, 0.2, 2.762]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={materials['beech wood']} position={[-0.034, 0, -7.659]} rotation={[-0.124, 0.855, 0.093]} scale={0.769} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.031']} position={[-0.114, 1.483, -7.725]} rotation={[1.516, 0.064, -0.859]} scale={[0.878, 0.655, 0.655]} />
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Material.007']} position={[4.97, 0.803, -2.583]} scale={[0.064, 0.056, 0.064]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.paper} position={[4.553, 0.747, -2.525]} rotation={[0, -0.541, 0]} scale={[0.125, 0.125, 0.082]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['meet screen']} position={[4.942, 0.753, -5.486]} rotation={[0, 0.018, 0]} scale={[0.041, 0.021, 0.041]} />
        <group name="Cube083" position={[17.219, 0.367, -1.35]}>
          <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.lightwood} />
          <mesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials['carpet.001']} />
          <mesh name="Cube017_2" geometry={nodes.Cube017_2.geometry} material={materials.floorrender} />
        </group>
        <mesh name="Box2567" geometry={nodes.Box2567.geometry} material={materials['Material.027']} position={[-4.057, 0.277, 5.124]} rotation={[Math.PI / 2, 0, -2.618]} scale={0.013} />
        <mesh name="Company_Logo_1001" geometry={nodes.Company_Logo_1001.geometry} material={materials.PaletteMaterial006} position={[-8.451, 3.12, -8.939]} scale={[0.341, 0.509, 0.059]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.PaletteMaterial005} position={[9.011, 1.372, -6.428]} rotation={[1.78, 0.493, -2.789]} scale={0.572} />
        <group name="Female013" position={[2.976, 0, -2.527]} rotation={[0, 0.528, 0]} scale={0.703}>
          <skinnedMesh name="Mesh015" geometry={nodes.Mesh015.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh015.skeleton} />
          <skinnedMesh name="Mesh015_1" geometry={nodes.Mesh015_1.geometry} material={materials['face.005']} skeleton={nodes.Mesh015_1.skeleton} />
          <skinnedMesh name="Mesh015_2" geometry={nodes.Mesh015_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh015_2.skeleton} />
          <skinnedMesh name="Mesh015_3" geometry={nodes.Mesh015_3.geometry} material={materials.green2} skeleton={nodes.Mesh015_3.skeleton} />
        </group>
        <group name="Object_81001" position={[-8.044, 0.017, -8.138]} rotation={[0, 0.706, 0]} scale={1.157}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0.geometry} material={materials['male_elegantsuit01.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0_1.geometry} material={materials.Face} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0_2.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0_2.skeleton} />
        </group>
        <group name="male_elegantsuit01Mesh_male_elegantsuit01_0002" position={[6.096, -0.383, -1.273]} rotation={[0, -1.561, 0]} scale={0.895}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0005" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005.geometry} material={materials['teal suit']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0005_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0005_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_2.geometry} material={materials['face2.002']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_2.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0005_3" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_3.geometry} material={materials.PaletteMaterial003} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0005_3.skeleton} />
        </group>
        <group name="Object_81002" position={[6.095, -0.376, -3.173]} rotation={[0, -1.476, 0]} scale={0.891}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0001" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001.geometry} material={materials['male_elegantsuit01.001']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0001_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001_1.geometry} material={materials.Face} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0001_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001_2.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0001_2.skeleton} />
        </group>
        <group name="male_elegantsuit01Mesh_male_elegantsuit01_0019" position={[1.645, -0.395, -3.165]} rotation={[0, -1.464, 0]} scale={0.891}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0019_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_1.geometry} material={materials['male_elegantsuit01.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0019_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_2.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_2.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0019_3" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_3.geometry} material={materials.face3} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_3.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0019_4" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_4.geometry} material={materials.PaletteMaterial003} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0019_4.skeleton} />
        </group>
        <group name="Object_81007" position={[4.067, -0.392, -5.47]} rotation={[0, 1.523, 0]} scale={0.907}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0004" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004.geometry} material={materials['male_elegantsuit01.007']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0004_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0004_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_2.geometry} material={materials.face3} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_2.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0004_3" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_3.geometry} material={materials.PaletteMaterial003} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0004_3.skeleton} />
        </group>
        <group name="Object_81" position={[4.096, -0.339, -7.227]} rotation={[0, 1.57, 0]} scale={0.843}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0021" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021.geometry} material={materials['male_elegantsuit01.006']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0021_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0021_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021_2.geometry} material={materials['face2.002']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0021_2.skeleton} />
        </group>
        <group name="Object_81010" position={[12.422, 0.022, -4.609]} rotation={[0, 1.488, 0]} scale={0.911}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0006" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006.geometry} material={materials.brownsuit2} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0006_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0006_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006_2.geometry} material={materials.face3} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0006_2.skeleton} />
        </group>
        <group name="Object_81005" position={[-8.618, -0.397, -4.241]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={1.022}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0007" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007.geometry} material={materials['male_elegantsuit01.006']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0007_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0007_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007_2.geometry} material={materials['face2.002']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0007_2.skeleton} />
        </group>
        <group name="Female002" position={[-10.081, -0.433, 4.236]} rotation={[0, 1.096, 0]} scale={0.992}>
          <skinnedMesh name="Mesh013" geometry={nodes.Mesh013.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh013.skeleton} />
          <skinnedMesh name="Mesh013_1" geometry={nodes.Mesh013_1.geometry} material={materials['Material.016']} skeleton={nodes.Mesh013_1.skeleton} />
          <skinnedMesh name="Mesh013_2" geometry={nodes.Mesh013_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh013_2.skeleton} />
          <skinnedMesh name="Mesh013_3" geometry={nodes.Mesh013_3.geometry} material={materials['Fabric mesh.003']} skeleton={nodes.Mesh013_3.skeleton} />
          <skinnedMesh name="Mesh013_4" geometry={nodes.Mesh013_4.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh013_4.skeleton} />
        </group>
        <group name="Object_81003" position={[-3.961, -0.488, -4.483]} rotation={[-Math.PI, -0.515, -Math.PI]} scale={1.095}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0010" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010.geometry} material={materials['cream suit2']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0010_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0010_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010_2.geometry} material={materials['face2.003']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0010_2.skeleton} />
        </group>
        <group name="Female005" position={[10.513, -0.376, -1.366]} rotation={[0, -Math.PI / 2, 0]} scale={0.961}>
          <skinnedMesh name="Mesh023" geometry={nodes.Mesh023.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh023.skeleton} />
          <skinnedMesh name="Mesh023_1" geometry={nodes.Mesh023_1.geometry} material={materials['face.005']} skeleton={nodes.Mesh023_1.skeleton} />
          <skinnedMesh name="Mesh023_2" geometry={nodes.Mesh023_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh023_2.skeleton} />
          <skinnedMesh name="Mesh023_3" geometry={nodes.Mesh023_3.geometry} material={materials['Fabric mesh.004']} skeleton={nodes.Mesh023_3.skeleton} />
          <skinnedMesh name="Mesh023_4" geometry={nodes.Mesh023_4.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh023_4.skeleton} />
        </group>
        <group name="Female008" position={[-6.502, -0.07, -3.778]} rotation={[-Math.PI, 0.038, -Math.PI]} scale={0.835}>
          <skinnedMesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh004.skeleton} />
          <skinnedMesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['Material.016']} skeleton={nodes.Mesh004_1.skeleton} />
          <skinnedMesh name="Mesh004_2" geometry={nodes.Mesh004_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh004_2.skeleton} />
          <skinnedMesh name="Mesh004_3" geometry={nodes.Mesh004_3.geometry} material={materials['Fabric mesh.003']} skeleton={nodes.Mesh004_3.skeleton} />
        </group>
        <group name="Female010" position={[-9.435, 0, -5.998]} rotation={[-Math.PI, 0.474, -Math.PI]} scale={0.707}>
          <skinnedMesh name="Mesh007" geometry={nodes.Mesh007.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh007.skeleton} />
          <skinnedMesh name="Mesh007_1" geometry={nodes.Mesh007_1.geometry} material={materials['face.005']} skeleton={nodes.Mesh007_1.skeleton} />
          <skinnedMesh name="Mesh007_2" geometry={nodes.Mesh007_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh007_2.skeleton} />
          <skinnedMesh name="Mesh007_3" geometry={nodes.Mesh007_3.geometry} material={materials.darkbluefabric} skeleton={nodes.Mesh007_3.skeleton} />
        </group>
        <group name="Female011" position={[-7.524, 0.285, -3.954]} rotation={[-Math.PI, 0.142, -Math.PI]} scale={1.246}>
          <skinnedMesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={nodes.Mesh001.material} skeleton={nodes.Mesh001.skeleton} />
          <skinnedMesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['face.002']} skeleton={nodes.Mesh001_1.skeleton} />
          <skinnedMesh name="Mesh001_2" geometry={nodes.Mesh001_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh001_2.skeleton} />
          <skinnedMesh name="Mesh001_3" geometry={nodes.Mesh001_3.geometry} material={materials['Fabric mesh.006']} skeleton={nodes.Mesh001_3.skeleton} />
        </group>
        <group name="Object_81011" position={[14.803, 0, 5.434]} rotation={[-Math.PI, 1.141, -Math.PI]} scale={0.758}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0008" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008.geometry} material={materials['male_elegantsuit01.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0008_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008_1.geometry} material={materials.Face} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0008_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008_2.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0008_2.skeleton} />
        </group>
        <group name="Female" position={[17.063, -0.069, 5.175]} rotation={[0, -1.052, 0]} scale={0.731}>
          <skinnedMesh name="Mesh021" geometry={nodes.Mesh021.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh021.skeleton} />
          <skinnedMesh name="Mesh021_1" geometry={nodes.Mesh021_1.geometry} material={materials['face.005']} skeleton={nodes.Mesh021_1.skeleton} />
          <skinnedMesh name="Mesh021_2" geometry={nodes.Mesh021_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh021_2.skeleton} />
          <skinnedMesh name="Mesh021_3" geometry={nodes.Mesh021_3.geometry} material={materials['Fabric mesh.003']} skeleton={nodes.Mesh021_3.skeleton} />
        </group>
        <group name="Female001" position={[5.641, -0.268, 3.956]} rotation={[0, -0.678, 0]} scale={0.654}>
          <skinnedMesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh002.skeleton} />
          <skinnedMesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials['Material.016']} skeleton={nodes.Mesh002_1.skeleton} />
          <skinnedMesh name="Mesh002_2" geometry={nodes.Mesh002_2.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Mesh002_2.skeleton} />
          <skinnedMesh name="Mesh002_3" geometry={nodes.Mesh002_3.geometry} material={materials['light blue']} skeleton={nodes.Mesh002_3.skeleton} />
        </group>
        <group name="Object_81012" position={[3.314, -0.422, 5.755]} rotation={[-Math.PI, 1.065, -Math.PI]} scale={0.794}>
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0009" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009.geometry} material={materials['male_elegantsuit01.006']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0009_1" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009_1.geometry} material={materials['shoes_oxford_male.005']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009_1.skeleton} />
          <skinnedMesh name="male_elegantsuit01Mesh_male_elegantsuit01_0009_2" geometry={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009_2.geometry} material={materials['face2.002']} skeleton={nodes.male_elegantsuit01Mesh_male_elegantsuit01_0009_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/combinedoffice-transformed.glb')
