/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tradeshow.glb --transform 
Files: tradeshow.glb [89.39MB] > C:\Users\aasth\OneDrive\Documents\StoryProc3D\src\models\tradeshow-transformed.glb [6.53MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tradeshow-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.39, 0.962, -0.803]} scale={0.885}>
        <mesh geometry={nodes.Plane011.geometry} material={materials.leather} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['tv1.001']} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group position={[-5.659, 0.963, -3.493]} rotation={[0.041, 0.924, -0.031]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials.laptop} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['tv2.001']} />
      </group>
      <group position={[-3.461, 0.064, 16.783]}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Cedar Wood Plank.001']} />
      </group>
      <group position={[10.864, 1.571, 10.039]} rotation={[-Math.PI, -0.167, -2.575]} scale={0.825}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Material.013']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.floorbake} position={[-8.845, -0.038, -6.133]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.PaletteMaterial004} position={[-8.845, -0.038, -6.133]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.030']} position={[-3.461, 0.019, 12.304]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.073, 4.006]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[1.786, 2.422, 9.442]} rotation={[Math.PI / 2, 0, -0.324]} scale={[0.763, 1, 1]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.PaletteMaterial005} position={[-2.392, 1.034, 9.362]} />
      <mesh geometry={nodes.Seating41_Seating41_388934.geometry} material={materials.PaletteMaterial006} position={[1.393, -0.029, 8.106]} rotation={[Math.PI / 2, 0, -1.573]} scale={0.003} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.006']} position={[-2.427, 1.783, 8.367]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.696, 1.113, 1.113]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials.PaletteMaterial007} position={[-6.653, 2.424, 9.452]} rotation={[Math.PI / 2, 0, 0.147]} scale={[0.763, 1, 1]} />
      <group position={[-7.782, 1.014, 12.174]} scale={[1, 0.883, 1]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials['Material.026']} />
      </group>
      <mesh geometry={nodes.Cube030.geometry} material={materials['Dark Steel']} position={[-7.808, 1.917, 12.065]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.022']} position={[11.233, 0.982, 9.143]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.woodplank2} position={[9.477, 0.019, -0.768]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.PaletteMaterial008} position={[9.881, 0.455, -5.432]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.010']} position={[9.465, 2.791, -1.719]} rotation={[0, 0, -Math.PI / 2]} scale={[0.625, 1, 1]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.029']} position={[12.781, 1.494, 7.524]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.grayboothbanner} position={[9.377, 1.494, 13.393]} />
      <group position={[11.771, 3.017, 8.112]} rotation={[0, 1.571, 0]} scale={0.074}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Dark Steel.002']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.PaletteMaterial009} />
      </group>
      <group position={[11.766, 0.019, 10.94]} scale={[1, 0.073, 4.006]}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.PaletteMaterial010} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.renderedfloortradeshow} position={[0, 0.04, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['rendered wall']} position={[-7.02, 3.844, 0]} />
      <mesh geometry={nodes.Curve.geometry} material={materials.PaletteMaterial011} position={[-4.617, 3.639, 1.928]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.PaletteMaterial012} position={[-4.178, 0.426, 1.753]} scale={[0.262, 0.348, 0.262]} />
      <group position={[1.704, 0.921, 1.527]} rotation={[Math.PI, -0.03, Math.PI]} scale={0.25}>
        <mesh geometry={nodes['39_laptop_39_laptop_445246_377861_Geometry001'].geometry} material={materials.tv1} />
        <mesh geometry={nodes['39_laptop_39_laptop_445246_377861_Geometry001_1'].geometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes['Electronics_Visual-TVs_Sony-Professional_FW-100BZ40J-10_c03001'].geometry} material={materials.tv2} position={[-0.683, 0.787, -5.913]} scale={[0.289, 0.305, 0.305]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['rendered wall 2']} position={[-9.144, 1.097, 0]} />
      <mesh geometry={nodes.Manuela_1654_OBJ.geometry} material={materials['Material.018']} position={[1.375, 0.148, 13.582]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Marina_1281_OBJ.geometry} material={materials['Default OBJ.002']} position={[-4.057, 0.111, -0.967]} rotation={[Math.PI / 2, 0, 1.503]} scale={0.001} />
      <mesh geometry={nodes.Inder_1194_OBJ.geometry} material={materials['Material.038']} position={[-0.208, 0.073, -3.549]} rotation={[Math.PI / 2, 0, -2.612]} scale={0.001} />
      <group position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001}>
        <mesh geometry={nodes.Rizzy_1372_COR001_1.geometry} material={materials['Default OBJ.009']} />
        <mesh geometry={nodes.Rizzy_1372_COR001_2.geometry} material={materials['Default OBJ.010']} />
        <mesh geometry={nodes.Rizzy_1372_COR001_3.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Rizzy_1372_COR001_4.geometry} material={materials['Material.039']} />
      </group>
      <mesh geometry={nodes.Rizzy_1372_COR006.geometry} material={materials['Default OBJ.003']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR009.geometry} material={materials['Default OBJ.008']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR011.geometry} material={materials['Default OBJ.006']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR013.geometry} material={materials.Nikhiel_1802_COR} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR016.geometry} material={materials['rizzy bake']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR017.geometry} material={materials['character group 1']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR018.geometry} material={materials['Default OBJ.007']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR019.geometry} material={materials['Default OBJ.004']} position={[13.557, 0.066, -4.715]} rotation={[Math.PI / 2, 0, -1.743]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR007.geometry} material={materials.Lewis_1714_COR} position={[1.225, 1.054, -3.413]} rotation={[Math.PI / 2, 0, -0.211]} scale={0.001} />
      <mesh geometry={nodes.Rizzy_1372_COR008.geometry} material={materials.Nikhiel_1797_VRY} position={[1.247, 1.096, -4.637]} rotation={[Math.PI / 2, 0, -0.211]} scale={0.001} />
      <instancedMesh args={[nodes.Plane009.geometry, materials['Material.002'], 5]} instanceMatrix={nodes.Plane009.instanceMatrix} />
      <instancedMesh args={[nodes.Plane004_1.geometry, materials['Material.010'], 5]} instanceMatrix={nodes.Plane004_1.instanceMatrix} />
      <instancedMesh args={[nodes.Dell1003.geometry, materials.PaletteMaterial013, 6]} instanceMatrix={nodes.Dell1003.instanceMatrix} />
      <instancedMesh args={[nodes.Seating24_Seating24_380469_380127_Geometry001.geometry, materials.PaletteMaterial006, 8]} instanceMatrix={nodes.Seating24_Seating24_380469_380127_Geometry001.instanceMatrix} />
      <instancedMesh args={[nodes.Seating24_Seating24_380469_380127_Geometry001_1.geometry, materials.PaletteMaterial004, 8]} instanceMatrix={nodes.Seating24_Seating24_380469_380127_Geometry001_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane006_1.geometry, materials.PaletteMaterial003, 9]} instanceMatrix={nodes.Plane006_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane006_2.geometry, materials.PaletteMaterial007, 9]} instanceMatrix={nodes.Plane006_2.instanceMatrix} />
      <instancedMesh args={[nodes.COR_Drop_Barstool_79102_Barstool_stackable_68cm_362127_d05070a.geometry, materials.PaletteMaterial006, 17]} instanceMatrix={nodes.COR_Drop_Barstool_79102_Barstool_stackable_68cm_362127_d05070a.instanceMatrix} />
      <instancedMesh args={[nodes.COR_Drop_Barstool_79102_Barstool_stackable_68cm_362127_d05070a_1.geometry, materials.PaletteMaterial012, 17]} instanceMatrix={nodes.COR_Drop_Barstool_79102_Barstool_stackable_68cm_362127_d05070a_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder.geometry, materials.PaletteMaterial012, 5]} instanceMatrix={nodes.Cylinder.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder_1.geometry, materials.PaletteMaterial011, 5]} instanceMatrix={nodes.Cylinder_1.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder_2.geometry, materials['Dark Steel.002'], 5]} instanceMatrix={nodes.Cylinder_2.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder002.geometry, materials['Dark Steel.002'], 5]} instanceMatrix={nodes.Cylinder002.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder002_1.geometry, materials.PaletteMaterial007, 5]} instanceMatrix={nodes.Cylinder002_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/tradeshow-transformed.glb')
